# Generated by Django 3.0.6 on 2020-05-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ORMAudience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_type', models.CharField(choices=[('S', 'Student'), ('T', 'Teacher'), ('G', 'General')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ORMNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=500)),
                ('news_content', models.TextField()),
                ('visible', models.BooleanField(default=True)),
                ('tags', models.CharField(max_length=500)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('audience', models.ManyToManyField(default='G', to='news.ORMAudience')),
            ],
            options={
                'verbose_name': 'ORMNews',
                'verbose_name_plural': 'ORMNews',
            },
        ),
    ]
