# Generated by Django 3.0.6 on 2020-05-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ORMAudience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_type', models.IntegerField(choices=[(1, 'Student'), (2, 'Teacher'), (3, 'General')])),
            ],
        ),
        migrations.CreateModel(
            name='ORMNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=500)),
                ('news_content', models.TextField()),
                ('visible', models.BooleanField(default=True)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('audience', models.ManyToManyField(to='news.ORMAudience')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
