# Generated by Django 3.0.6 on 2020-05-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('initiatives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ORMNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.IntegerField()),
                ('news_title', models.CharField(max_length=500)),
                ('news_content', models.TextField()),
                ('visible', models.BooleanField()),
                ('publish_date', models.DateTimeField()),
                ('initiatives', models.ManyToManyField(to='initiatives.ORMInitiative')),
            ],
        ),
    ]
