# Generated by Django 3.0.6 on 2020-05-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ormnews',
            options={'verbose_name': 'ORMNews', 'verbose_name_plural': 'ORMNews'},
        ),
        migrations.AlterField(
            model_name='ormaudience',
            name='audience_type',
            field=models.CharField(choices=[('S', 'Student'), ('T', 'Teacher'), ('G', 'General')], max_length=1),
        ),
    ]
