# Generated by Django 3.0.6 on 2020-05-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ORMInitiative',
            fields=[
                ('init_id', models.AutoField(primary_key=True, serialize=False)),
                ('acronym', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=30)),
            ],
        ),
    ]
