# Generated by Django 3.0.6 on 2020-05-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orminitiative',
            name='acronym',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='orminitiative',
            name='full_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
